### ISSUE TITLE
Toolset menu missing?

### ISSUE THREAD

**Issue by HelmoHass** [Micky1979/Clover-Configurator-Pro#2]
Hi,
Me again, I guess i've found what to me really seem to be a strange behaviour.
I noticed that differently from when launched with clover facilities
![screen shot 1](https://user-images.githubusercontent.com/33957277/34455782-b4ac3a0c-ed86-11e7-873d-f6c330ff4d33.png)
opening the application in editor only you have no more the menu options to recall any tool 
![screen shot](https://user-images.githubusercontent.com/33957277/34455767-5c7a6e94-ed86-11e7-997c-8d7c353e3e70.png)
which is a pity imo since if you like use it as primary plist-editor, you'r forced to modify the preferences and restart the application everytime.

PS
I've noticed the changes in b5, but I guess I wasn't considering a few more aspects
1) BuildCloverConfig.txt
many also may have edited the ".bash_profile" and keeping their copy elsewhere, no big deal since Build_Clover will anyway point to the one specified in the profile, but we'll always be forced to delete the duplicate created by default,
2) CCP  (could also be customized)

So my question/suggestion would be, 
would it be possible in addition to the current configuration, add the possibility ie: for users to define their export_path into that same .bash_profile (as they already do for BuildCloverConfig.txt), so once your app is launched if a path is already defined it will use that one, otherwise since you already made Pandora's Box (which create as well a directory) you could use a common directory for all.  ie: ~/MickyToolset/Pbox ~/MickyToolset/CCP

Cheers

**Comment by Micky1979** [comment]
Sorry for the late but I was in London for the the end of the year... and from London I brought home a bad flu and I took to revive me today.

> which is a pity imo since if you like use it as primary plist-editor, you'r forced to modify the preferences and restart the application everytime.

Sorry Bro, but who say that? If you need them why not just leave the option "Load Clover Configurator Pro.app as a normal plist Editor (no Clover facilities)"  disabled?? In Beta 6 this is even enforced because normal users will have to unlock Clover stuff with administrative user-password, so only Administrators can unlock them. I don't think normal users should have the right to change bootloader,  the config or the NVRAM.
Anyway With that option enabled now will have the two text/data converters enabled end selectable. Can be usefull.

> PS
> I've noticed the changes in b5, but I guess I wasn't considering a few more aspects
> 
> BuildCloverConfig.txt
> many also may have edited the ".bash_profile" and keeping their copy elsewhere, no big deal since Build_Clover will anyway point to the one specified in the profile, but we'll always be forced to delete the duplicate created by default,
> CCP (could also be customized)
> So my question/suggestion would be,
> would it be possible in addition to the current configuration, add the possibility ie: for users to define their export_path into that same .bash_profile (as they already do for BuildCloverConfig.txt), so once your app is launched if a path is already defined it will use that one, otherwise since you already made Pandora's Box (which create as well a directory) you could use a common directory for all. ie: ~/MickyToolset/Pbox ~/MickyToolset/CCP

Glad that someone uses the  .bash_profile for Build_Clover.command. That functionality was introduced just for this application, this is in a working state in Beta 6.
~/MickyToolset/Pbox ~/MickyToolset/CCP?  Sorry here can't understand you. No one here mentioned the "hackintosh" word just because this is not a hackintosh app and Pandora's box has nothing to do with Clover Configurator Pro. Also the ~/CCP directory is only created if you do something like download the bootloader, or you installed the bootloader and here you can find the backup. Moreover the backup happens without taking elevated privileges and I can not allow this to happen in a path where you do not have permission to write. 
So no this cannot be accepted, sorry!
